export const TUTORIAL_REQUEST="TUTORIAL_REQUEST"
export const TUTORIAL_SUCCESS="TUTORIAL_SUCCESS"
export const TUTORIAL_FAIL="TUTORIAL_FAIL"

export const UPDATE_REQUEST="UPDATE_REQUEST"
export const UPDATE_SUCCESS="UPDATE_SUCCESS"
export const UPDATE_FAIL="UPDATE_FAIL"

export const LIST_REQUEST="LIST_REQUEST"
export const LIST_SUCCESS="LIST_SUCCESS"
export const LIST_FAIL="LIST_FAIL"

export const DELETE_REQUEST="DELETE_REQUEST"
export const DELETE_SUCCESS="DELETE_SUCCESS"
export const DELETE_FAIL="DELETE_FAIL"